"""Domain-neutral plot specifications, style policy, and renderers."""

from ._version import __version__
from .analysis_artists import (
    plot_field_regime_splits,
    plot_lineshape_comparison,
)
from .config import FigureConfig
from .matplotlib import (
    RenderResult,
    render_heatmap,
    render_line_plot,
    render_poincare_scatter,
    render_poincare_trajectory,
    render_multi_surface_3d,
    render_polarization_ellipses,
    render_polarization_angles,
    render_surface_3d,
    render_vector_field,
)
from .models import (
    AxesSpec,
    ColorMappedLineSeries,
    ColorMappedLineStyle,
    FigureSpec,
    HeatmapPlotSpec,
    HeatmapStyle,
    LinePlotSpec,
    LineSeries,
    MultiSurfacePlotSpec,
    RibbonSeries,
    RibbonStyle,
    SeriesStyle,
    SurfaceLayer,
    SurfaceStyle,
    VectorFieldPlotSpec,
    VectorFieldStyle,
)
from .runtime import RuntimeInfo, runtime_info
from .legacy_line import plot_line_advanced
from .legacy_heatmap import plot_2d_heatmap
from .legacy_scatter import plot_scatter_advanced
from .legacy_contour import (
    extract_contour_paths,
    extract_isofreq_paths,
    plot_iso_contours2D,
    plot_paths,
)
from .legacy_multiline import plot_1d_lines, plot_2d_multiline
from .legacy_basic import add_annotations, draw_shapes
from .legacy_polar import imshow_phi, imshow_s3, plot_polar_line
from .style import (
    OVERVIEW_FIGURE,
    DIAGNOSTIC_PROFILE,
    PAPER_FIGURE,
    PAPER_PROFILE,
    PAPER_STYLE,
    PREVIEW_PROFILE,
    PUBLICATION_MINIMAL_PROFILE,
    FigurePolicy,
    FigurePreset,
    MatplotlibStyle,
    PlotProfile,
    SaveSpec,
    figure_preset,
    profile,
    profile_context,
    save_figure,
    style_context,
)

__all__ = [
    "AxesSpec",
    "ColorMappedLineSeries",
    "ColorMappedLineStyle",
    "FigureSpec",
    "FigureConfig",
    "HeatmapPlotSpec",
    "HeatmapStyle",
    "FigurePreset",
    "FigurePolicy",
    "LinePlotSpec",
    "LineSeries",
    "MultiSurfacePlotSpec",
    "MatplotlibStyle",
    "OVERVIEW_FIGURE",
    "DIAGNOSTIC_PROFILE",
    "PAPER_FIGURE",
    "PAPER_PROFILE",
    "PAPER_STYLE",
    "PREVIEW_PROFILE",
    "PUBLICATION_MINIMAL_PROFILE",
    "PlotProfile",
    "RenderResult",
    "RibbonSeries",
    "RibbonStyle",
    "RuntimeInfo",
    "SaveSpec",
    "SeriesStyle",
    "SurfaceLayer",
    "SurfaceStyle",
    "VectorFieldPlotSpec",
    "VectorFieldStyle",
    "__version__",
    "plot_field_regime_splits",
    "plot_lineshape_comparison",
    "render_line_plot",
    "render_heatmap",
    "render_polarization_ellipses",
    "render_polarization_angles",
    "render_poincare_scatter",
    "render_poincare_trajectory",
    "render_multi_surface_3d",
    "render_surface_3d",
    "render_vector_field",
    "figure_preset",
    "profile",
    "profile_context",
    "plot_line_advanced",
    "plot_2d_heatmap",
    "plot_scatter_advanced",
    "extract_contour_paths",
    "extract_isofreq_paths",
    "plot_iso_contours2D",
    "plot_paths",
    "plot_1d_lines",
    "plot_2d_multiline",
    "draw_shapes",
    "add_annotations",
    "plot_polar_line",
    "imshow_phi",
    "imshow_s3",
    "runtime_info",
    "save_figure",
    "style_context",
]
